# Секреты для приложения ReflexAI
# Эти значения должны быть установлены как переменные окружения на Koyeb

# Пароль для доступа к админ-панели и для изменения URL мониторинга
ADMIN_PASSWORD="6519565195"

# Секретный ключ для генерации и проверки JWT токенов
JWT_SECRET="YOUR_VERY_STRONG_JWT_SECRET_KEY"

# URL сервера LLaMA (например, ваш ngrok URL)
LLAMA_SERVER_URL="https://your-ngrok-tunnel-id.ngrok-free.app"
